### ISSUE TITLE
Cannot find React

### ISSUE THREAD

**Issue by anthony-bernardo** [React-Sight/React-Sight#134]
I got : 'Cannot find React', I tried to enter 'setState()' in console, but I got : 

> Uncaught ReferenceError: setState is not defined
>     at <anonymous>:1:1

Am I doing something wrong ?

**Comment by davidcsally** [comment]
Hi @xero88, thanks for giving React Sight a try. Our general error message means that React-Sight wasn't able to inject it's rendering patch into the React code. Ideally, when the dev tools are opened, React Sight will find the root div that React renders to, and patch the render function. However, if React-Sight can't find the render function, it will 'wait' for a render event to fire, and then patch the code from there.

If you can trigger a re-render (eg props change, state change, route change, redux change) while React-Sight is opened, it should hopefully fix the problem. Unfortunately, you can't manually call the setState() function in the console - it's internal to the React library

**Comment by bttf** [comment]
hello; i've tried triggering re-renders within my app and have done so several ways but react-sight is still unable to latch on. is there any method you'd recommend to help debugging this, or perhaps where to look to find out more information?

**Comment by AntonVoltchok** [comment]
This is an identical issue that React dev tools has, my solution to this when I get it is to change routes, maybe go to the main view of the app and refresh there, or just try to refresh the app on different views other than where you are currently. So after you find a route that worked and react dev tools or sight loads, then you can navigate to the original route where you had this problem and then you can view it without issues.

**Comment by ChristianDavis** [comment]
I can't get this library to find any react project, even basic CRA projects in 14, 15, 16. Is there a specific hook I'm missing that's not in the docs?

 have react Dev Tools > install extension > run React app

**Comment by davidcsally** [comment]
@ChristianDavis are you able to see your app in react-dev-tools? Does triggering a setState / re-render cause it to show up in either extensions? If you have a test repo that replicates this I can take a look at it

**Comment by ChristianDavis** [comment]
Yeah, If you download and run the example app, https://github.com/react-boilerplate/react-boilerplate, react dev tools works and react-sight stays on the Cannot find React message. I'm on latest Chrome, 66.0.3359.181

**Comment by ChristianDavis** [comment]
@davidcsally btw, love the idea of the graph display. We use graphs as data structures in a number of projects, not always visualized. If you need help figuring out what's going on, let me know. I'm excited to try it out

**Comment by gtdeng** [comment]
I'm getting the same issue with React 15.6.

**Comment by givik** [comment]
Same issue on react 16.4.1.

<img width="1440" alt="screen shot 2018-07-25 at 4 52 20 pm" src="https://user-images.githubusercontent.com/2458760/43201986-295cbf56-902b-11e8-8dde-514657381b55.png">

**Comment by acarl005** [comment]
Same issue with react 16.4.2 and latest chrome on mac

**Comment by DiederikvandenB** [comment]
Yup, same here.

**Comment by mathieuroblin** [comment]
Exact same situation for me. React 16.4.2, React-dev-tools work, and also running on chrome

**Comment by biels** [comment]
Exact same situation for me. React 16.5.2, React-dev-tools work, and also running on chrome

**Comment by najisawas** [comment]
same issue, using react 16.5.2, and a working react-dev-tools...

**Comment by lvtianyu** [comment]
the same issue，using react 16.6.3 React-Sight

**Comment by biels** [comment]
Maybe the replacement could be added to labs meanwhile?

**Comment by davidcsally** [comment]
Hi all, unfortunately it looks like its no longer working in React ~16.6.3. We built this out using "experimental" unstable under hood APIs in React. I would like to refactor our custom virtual DOM parser to simply accept the data from React DevTools, since that would do the heavy lifting for us, but I am not sure when I will have time. Possibly around the holidays. Sorry for the broken extension in the mean time. If you'd like to take a stab, please knock yourself out!

**Comment by BarishSarac** [comment]
Any update @davidcsally?

**Comment by eaverdeja** [comment]
Here it doesn't work, even on navigation. I'm using react 16.8.1 and not one class component for handling state or effects, it's hooks all the way. I'm still very excited to see this working!!

**Comment by davidcsally** [comment]
Hey everyone, sorry for stringing ya'll along. I don't really have the time to maintain this anymore. If anyone is interested in talking a look, feel free to @ me and we can figure out a way to collaborate. I'm happy to help anyone that would like to contribute.

**Comment by e0da** [comment]
@davidcsally Thank you for all the work you've done so far. :heart:

**Comment by michaelcmelton** [comment]
@davidcsally Is this project no longer maintained?

**Comment by davidcsally** [comment]
@michaelcmelton it's no longer maintained :(

**Comment by coryhouse** [comment]
Since this isn't maintained and doesn't work, I suggest marking the repo and extension as such to avoid wasting people's time setting it up.

**Comment by South-Paw** [comment]
What @coryhouse said.

Please ensure that your website/docs should state that this is currently not working - especially since you guys know it is not working and don't intend to fix it anytime soon.

**Comment by golestanirad** [comment]
is there any alternative tool? PLEASE

**Comment by michaelcmelton** [comment]
@davidcsally What would it take to get this put back online??

**Comment by michaelcmelton** [comment]
@davidcsally To clarify, I’m interesting in collaborating and helping contribute to get this extension back usable again.

**Comment by solancer** [comment]
same issue

**Comment by laurencefass** [comment]
same issue. subscribed.

**Comment by angarag** [comment]
same issue. Chrome Version 78.0.3904.108, React v16

**Comment by alex-engelmann** [comment]
Would be nice if the project's readme explained that it doesn't work.  30 minutes of my life wasted.  Using Chrome Version 78.0.3904.108 and React 16.10.1

**Comment by golestanirad** [comment]
> Would be nice if the project's readme explained that it doesn't work. 30 minutes of my life wasted. Using Chrome Version 78.0.3904.108 and React 16.10.1

That project saved millions of minutes of developers' lifetime when it was working so I guess the way that you say 30 minutes of yours was wasted is a bit mean, though, I totally agree that they need to report it on the website as well.

**Comment by IanWalston** [comment]
this extension no longer works

**Comment by davidcsally** [comment]
Stay tuned! I actually fixed it here https://github.com/React-Sight/React-Sight/pull/147

**Comment by davidcsally** [comment]
It's lit 🔥Still some bugs to work through, but it works again! Version 1.1.0 has been published to the Chrome webstore, so hopefully it will be released soon! In the meantime, I will make the documentation clear on how to build your own version of this from this repository. It's actually really easy!

See - https://github.com/React-Sight/React-Sight/pull/176

**Comment by davidcsally** [comment]
For anyone that wants to try this out now, I've update the instructions for building the extension locally!  https://github.com/React-Sight/React-Sight/pull/177

**Comment by davidcsally** [comment]
I’ve also ported the fixed version to Firefox, where the new version is now live!  Available here: https://addons.mozilla.org/en-US/firefox/addon/react-sight/

**Comment by davidcsally** [comment]
Released! https://chrome.google.com/webstore/detail/react-sight/aalppolilappfakpmdfdkpppdnhpgifn

**Comment by cksachdev** [comment]
@davidcsally I am still getting the same error. Tried navigating to different views as well, but no luck. 
Version: 1.1.0
![image](https://user-images.githubusercontent.com/37770/78131779-3fc42b00-7439-11ea-9487-2c7b351b61a7.png)

**Comment by akhilnukala** [comment]
@davidcsally getting the same "Cannot find React" error...tried different things...but to no avail

**Comment by biels** [comment]
There are things that never change 😄 Looks like Cannot find React is one of them

**Comment by davidcsally** [comment]
Sorry I haven't been too responsive, I think the core problem here for so many people is that this doesn't work on many server side rendering setups, specifically things like gatsby or react-snap. I am pretty sure this works on all client rendered applications. I'm going to update the readme and in app error message to say something along the lines of :

>"Note: server side rendering and pre-rendering may not work".

**Comment by davidcsally** [comment]
OK so with this bay area quarantine I've actually started looking into this. The root cause is the janky cloning method I am using to send data from the window to the chrome extension: `JSON.parse(JSON.stringify(ReactSightData))`.

(see `traverse16` in `fiber-hook`)

I am pretty sure the problem for everyone here is this: `clone error: TypeError: Converting circular structure to JSON`. So I will have to reimplement this clone method in a safer way. 

I noticed that the `emotion` package causes this to fail - I imagine there's a bunch of other popular packages that throw this error too.  Hopefully one fix will fix all of this!

**Comment by davidcsally** [comment]
OK I am pretty sure I fixed this, there were two major bugs:

1. Trying to read `store()` when it was undefined would throw an error 
2. Trying to convert circular references would throw an error

I fixed 1. by wrapping in a try/catch, and 2. by using the [circular package](https://www.npmjs.com/package/circular) to filter out circular references.

I've tested this on a few different websites that it wasn't working on previously, and it worked!

Expect a PR soon!

**Comment by davidcsally** [comment]
Should be fixed here: https://github.com/React-Sight/React-Sight/pull/202

I'll post another update when its published on the chrome / FF stores

**Comment by davidcsally** [comment]
New version up for firefox: https://addons.mozilla.org/en-US/firefox/addon/react-sight/

Chrome bundle has been uploaded but will probably take a few days to pass review

**Comment by dancomanlive** [comment]
Glad to hear we got an update but it's unfortunately not working for me on Firefox :( Same error message "Connot find React". It also seems to be creating multiple instances:

![Screen Shot 2020-04-12 at 12 45 08 PM](https://user-images.githubusercontent.com/16872821/79066900-8fb5b400-7cbb-11ea-8576-cd902d55530d.png)

**Comment by prescottprue** [comment]
Still seeing the same too in Chrome and I'm not using any server side rendering. I'm also seeing the following in the console:

![image](https://user-images.githubusercontent.com/2992224/90155717-a21f2780-dd59-11ea-991a-cc88afe78447.png)

**Comment by Jason2B3** [comment]
I think I've figured out a bugfix that's fairly easy to implement on any project
1. Create a new JS file on the same level as App.js called ActivateSight.js (include the snippet below)
`
import { useState } from "react";

function ActivateSight() {
  const [title, setTitle] = useState("");
  const clickHandler = () => {
    console.log(title);
    setTitle("UPDATED");
  };  
  const btnStyle={
    height:'80px',
  }
  return (<button style={btnStyle} onClick={clickHandler}>React-sight activate!</button>)
}
export default ActivateSight;
`
2. At the top of the App.js file, include this line:
`import ActivateSight from "./ActivateSight";`

3. Include the following in your App.js JSX (preferably at the bottom as its last element)
`<ActivateSight/>`

When you open a live preview of your page with npm start, you'll find a button somewhere that says "React-sight activate!". Hit it and the component tree should render properly
